## Find the min, max, mean, sum (tensor aggregation)

In [1]:
import torch

In [2]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [3]:
x.min(), x.max(), torch.max(x)

(tensor(0), tensor(90), tensor(90))

In [4]:
# torch.mean(x) # won't work with dtype int64 because it Long

In [5]:
torch.mean(x.type(dtype=torch.float32)), x.type(dtype = torch.float32).mean()

(tensor(45.), tensor(45.))

In [6]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [7]:
x.argmax(), x.argmin(), x.argsort()

(tensor(9), tensor(0), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

## Finding the positional min and max

In [8]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
x.argmin(), x[0] # it will find the min index value

(tensor(0), tensor(0))

In [10]:
y = torch.arange(1,100,10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
y.argmin(), y[0]

(tensor(0), tensor(1))

In [12]:
x.argmax(), x[9] # it will find the max index value


(tensor(9), tensor(90))

In [13]:
y.argmax() , y[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing, unsqueezing the tensors

- Reshaping: Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
- View: Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- Stacking: Combine multiple tensors on top of each other(vstack) or side by side(hstack)
- Squeezing: Squeezes input to remove all the dimenions with value 1.
- Unsqueezing: Returns input with a dimension value of 1 added at dim.
- Permute: Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [14]:
# lets create a tensor
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [15]:
# reshape the above tensor
x_reshaped = x.reshape(1,9) # we can only add the multiples of 9 because above we have size 9, means 3x3, 9x1, 1x9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [16]:
# change the view
z = x.view(1,9)
x, z

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [17]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
# changing z changes x (because a view of tensor shares a same memory as the original tensor)
z[:,0] = 5
x, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [19]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x], dim=0)  # dim = 0 means vstack(vertical stacking)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
x_stacked = torch.stack([x,x,x], dim=1)  # dim = 1 means vstack(horizontal stacking)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [21]:
a = torch.arange(1,10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a_stacked = torch.stack([a,a], dim=1)  # dim = 1 means vstack(horizontal stacking)
a_stacked

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5],
        [6, 6],
        [7, 7],
        [8, 8],
        [9, 9]])

In [23]:
# torch.squeeze() => removes all the dimension 1 tensor from the target tensor

In [24]:
a = torch.tensor([2,1,2,3,2,1])
a

tensor([2, 1, 2, 3, 2, 1])

In [25]:
a.size()

torch.Size([6])

In [26]:
b = a.squeeze()
b, b.size()

(tensor([2, 1, 2, 3, 2, 1]), torch.Size([6]))

In [27]:
print(f"Previous tensor: {a}")
print(f"Previous shape: {a.shape}")

# Remove extra dimension from b
b = a.squeeze()
print(f"\nNew tensor: {b}")
print(f"New shape: {b.shape}")

Previous tensor: tensor([2, 1, 2, 3, 2, 1])
Previous shape: torch.Size([6])

New tensor: tensor([2, 1, 2, 3, 2, 1])
New shape: torch.Size([6])


In [28]:
# torch.unsqueeze() => add the dimension 1 tensor to the target tensor

In [29]:
print(f"Previous tensor: {b}")
print(f"Previous shape: {b.shape}")

# add extra dimension with c
c = b.unsqueeze(dim=0)
print(f"\nNew tensor: {c}")
print(f"New shape: {c.shape}")

Previous tensor: tensor([2, 1, 2, 3, 2, 1])
Previous shape: torch.Size([6])

New tensor: tensor([[2, 1, 2, 3, 2, 1]])
New shape: torch.Size([1, 6])


In [30]:
# torch.permute() => rearranges the dimensions of a target tensor in a specified order

In [31]:
p = torch.randn(50,100,200)

In [32]:
p.permute([2,0,1]).size() # shifts 0 -> 2, 1 -> 0, 2 -> 1

torch.Size([200, 50, 100])

## Indexing (selecting data from tensors)
- Indexing with PyTorch is same as the indexing with numpy

In [33]:
# creating a tensor
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [34]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
# lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [36]:
# lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [37]:
# x[1][1][1] # it will give an error of indexing

In [38]:
# we can also use ":" to select all the target things in the tensors

In [39]:
x[:, 0] # this means that all from initial dimension and 0 from next dimension

tensor([[1, 2, 3]])

In [40]:
x[:,:,0] # this means that all from initial dimension and all from next dimension and 0th element from next dimension

tensor([[1, 4, 7]])

In [41]:
x[:,1,1]

tensor([5])

In [42]:
x[0,0,:]

tensor([1, 2, 3])

In [43]:
# index on x to return 9
print(x[:,2,2])
print(x[0][2][2])

tensor([9])
tensor(9)


In [44]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and Numpy
### Numpy is a popular scientific python numerical computing library
### And because of this, PyTorch has fucntionality to intract with it.
- Data in Numpy, want it in PyTorch tensor => torch.from_numpy(ndarray)
- PyTorch tensor -> Numpy => torch.tensor.numpy()

In [45]:
import numpy as np

In [46]:
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [47]:
array.dtype, tensor.dtype # default numpy dtype is "float64"

(dtype('float64'), torch.float64)

In [48]:
# and default pytorch dtype is "float32"
torch.arange(1.,8.).dtype

torch.float32

In [49]:
# so we have to change the dtype to float32
# when converting from numpy to pytorch, pytorch reflects numpy's default dtype which is float64 unless specified otherwise
a = torch.from_numpy(array).type(torch.float32)
a.dtype

torch.float32

In [50]:
# change the value of the array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
# it add 1 to array but the tensor is same because these both does not share the same memory.

In [52]:
# and same in case of tensor to array
tensor = tensor + 2
tensor, array

(tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [53]:
# Tensor to Numpy
tensor1 = torch.ones(6)
numpy_tensor = tensor1.numpy()
tensor1, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1.], dtype=float32))

In [54]:
tensor1.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [55]:
tensor1

tensor([1., 1., 1., 1., 1., 1.])

## Reproducibility (trying to take random out of random)

In short how a neural networks learns:
It starts with random numbers -> tensor operations -> update random number to try and make them better representations of the data -> again -> again -> again.....

- To reduce the randomness in the neural networks, PyTorch comes with the concept of **random seed**.

- Essentially what the **random seed** does is flavour the randomness.

In [56]:
torch.rand(3,3)

tensor([[0.0782, 0.1852, 0.4112],
        [0.4460, 0.6222, 0.9058],
        [0.4799, 0.3750, 0.9734]])

In [57]:
rand_tensor_a = torch.rand(3,3)
rand_tensor_b = torch.rand(3,3)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.6841, 0.7324, 0.6626],
        [0.2039, 0.5427, 0.9607],
        [0.6503, 0.9221, 0.2122]])
tensor([[0.0277, 0.0953, 0.8256],
        [0.9985, 0.3569, 0.9673],
        [0.8059, 0.2371, 0.2884]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [58]:
## By applying the random see

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_tensor_c = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
rand_tensor_d = torch.rand(3,3)

print(rand_tensor_c)
print(rand_tensor_d)
print(rand_tensor_c == rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = Faster computations on numbers, thanks to CUDA + NVIDIA and PyTorch for working behind the scenes to make everything hunky dory(everything going well).


# getting a GPU
1. Easiest -> use Google Colab for a free GPU (Options to upgrade as well)
2. Use our own GPU -> Takes a little bit of setup and requires investment of purchasing a GPU, there's alot of options
the post for what options we can choose: https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. We can use cloud computing -> GCP, AWS, Azure, these services allowed you to rent the computers on the cloud and access them

In [59]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [60]:
# if we are using the cpu then following output will come
# /bin/bash: line 1: nvidia-smi: command not found

## 2. Check for GPU access with PyTorch

In [61]:
# cheking the gpu access
torch.cuda.is_available()

False

In [62]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [63]:
# count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors and (models) on the GPU
- The resean we want our tensors/models on GPU is because using a GPU results in faster computing.

In [64]:
# create a tensor (default on GPU)
tensor = torch.tensor([1,2,3], device = "cpu")

In [65]:
# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [66]:
# Move tensor to GPU(If available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## 4. Moving tensors back to the CPU

In [67]:
# if the tensor is on gpu and can't transform it to Numpy
# tensor_on_gpu.numpy() # this will give an error

In [68]:
# To fix the GPU tensor with numpy issue, we can first set it to the GPU.
tensor_back_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_gpu

array([1, 2, 3])