In [1]:
import torch

### Create a random tensor with shape (7, 7).

In [2]:
tensor = torch.rand(7,7)
tensor

tensor([[0.9662, 0.5837, 0.0491, 0.0851, 0.1213, 0.9147, 0.6175],
        [0.0724, 0.7075, 0.0405, 0.8021, 0.2665, 0.7804, 0.9329],
        [0.9368, 0.4058, 0.9430, 0.8124, 0.2225, 0.5331, 0.8034],
        [0.0510, 0.4914, 0.4449, 0.2115, 0.7505, 0.0765, 0.1731],
        [0.9477, 0.4872, 0.4840, 0.0297, 0.6994, 0.2431, 0.5672],
        [0.1538, 0.9858, 0.8654, 0.9771, 0.4196, 0.5262, 0.6413],
        [0.8234, 0.0697, 0.5393, 0.1356, 0.7038, 0.1840, 0.3429]])

### Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
tensor_1 = torch.rand(size=(1,7))
tensor_1

tensor([[0.2335, 0.4497, 0.9534, 0.1385, 0.2124, 0.8927, 0.9359]])

In [4]:
tensor_1.matmul(tensor)

tensor([[2.2676, 1.9581, 2.3705, 2.1899, 1.6461, 1.7770, 2.3675]])

In [5]:
torch.matmul(tensor, tensor_1.T)

tensor([[1.9669],
        [2.1111],
        [2.6879],
        [1.0760],
        [1.8022],
        [2.5987],
        [1.3912]])

### Set the random seed to 0 and do exercises 2 & 3 over again.

In [6]:
random_seed = 0
torch.manual_seed(random_seed)
tensor_a = torch.rand(7,7)

torch.manual_seed(random_seed)
tensor_b = torch.rand(size=(1,7))

print(tensor_a)
print(tensor_b)
print(torch.matmul(tensor_a, tensor_b.T))
print((torch.matmul(tensor_a, tensor_b.T)).shape)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])
torch.Size([7, 1])


### Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [7]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device: ", device)

device:  cuda


In [10]:
tensor_A = torch.rand(size=(4,3)).to(device)
tensor_B = torch.rand(size=(4,3)).to(device)
print(tensor_A)
print(tensor_B)

tensor([[0.8839, 0.8083, 0.7528],
        [0.8988, 0.6839, 0.7658],
        [0.9149, 0.3993, 0.1100],
        [0.2541, 0.4333, 0.4451]], device='cuda:0')
tensor([[0.4966, 0.7865, 0.6604],
        [0.1303, 0.3498, 0.3824],
        [0.8043, 0.3186, 0.2908],
        [0.4196, 0.3728, 0.3769]], device='cuda:0')


### Perform a matrix multiplication on the tensors you created above (again, you may have to adjust the shapes of one of the tensors).

In [13]:
print(torch.matmul(tensor_A, tensor_B.T).shape)
torch.matmul(tensor_A, tensor_B.T)

torch.Size([4, 4])


tensor([[1.5718, 0.6858, 1.1873, 0.9559],
        [1.4900, 0.6492, 1.1635, 0.9208],
        [0.8411, 0.3010, 0.8951, 0.5742],
        [0.7609, 0.3548, 0.4718, 0.4359]], device='cuda:0')

### Find the maximum and minimum values of the output of above

In [14]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output)

print(torch.max(output))
print(torch.min(output))

tensor([[1.5718, 0.6858, 1.1873, 0.9559],
        [1.4900, 0.6492, 1.1635, 0.9208],
        [0.8411, 0.3010, 0.8951, 0.5742],
        [0.7609, 0.3548, 0.4718, 0.4359]], device='cuda:0')
tensor(1.5718, device='cuda:0')
tensor(0.3010, device='cuda:0')


### Find the maximum and minimum index values of the output

In [17]:
print(output)

print(torch.argmax(output))
print(torch.argmin(output))

tensor([[1.5718, 0.6858, 1.1873, 0.9559],
        [1.4900, 0.6492, 1.1635, 0.9208],
        [0.8411, 0.3010, 0.8951, 0.5742],
        [0.7609, 0.3548, 0.4718, 0.4359]], device='cuda:0')
tensor(0, device='cuda:0')
tensor(9, device='cuda:0')


### Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [19]:
torch.manual_seed(7)

rand_tensor = torch.rand(size=(1,1,1,10))

rand_tensor1 = rand_tensor.squeeze()

print(rand_tensor, rand_tensor.shape)
print(rand_tensor1, rand_tensor1.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
